#!/usr/bin/env python3
"""
build_installer.py

The app is three sources. What ships is one file. Writing the Python twice,
once as source and once inside the shell script, is the failure the manifest
names by name: two copies with a rule about keeping them in step are still two
copies, and the rule is eventually not followed. So the installer is GENERATED,
the sources are the truth, and --check fails when the shipped file is stale.

    python3 tools/build_installer.py            write the installer
    python3 tools/build_installer.py --check    exit 1 if it is stale

The version comes from src/10_app.py, from VERSION, and from nowhere else.
The filename carries that number at both ends, per modules/versioning.md.
"""

import hashlib, os, re, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import engine_patches

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEAD = os.path.join(ROOT, "src", "00_head.sh")
TRANSCRIBE = os.path.join(ROOT, "src", "30_transcribe.html")
SEED = os.path.join(ROOT, "src", "seed")
PAGE = os.path.join(ROOT, "src", "15_page.html")
APP = os.path.join(ROOT, "src", "10_app.py")
TAIL = os.path.join(ROOT, "src", "20_tail.sh")

# The reader ships as files beside the app, not as strings inside it. Each one
# goes into the installer through its own heredoc, and each heredoc has its own
# marker — so each one needs checking for that marker in its own content, or a
# file containing it would end its heredoc early and the rest of the installer
# would be read as shell. That failure produces a file truncated at a plausible
# place and a pile of command-not-found, which is a bad afternoon.
READER_PARTS = [
    ("@@READER_PY@@",       "41_reader.py",     "GTT_READER_PY_EOF"),
    ("@@VOICESEX_PY@@",     "42_voicesex.py",   "GTT_VOICESEX_EOF"),
    ("@@READER_HTML@@",     "45_reader.html",   "GTT_READER_HTML_EOF"),
    ("@@MARKED_JS@@",       "46_marked.umd.js", "GTT_MARKED_EOF"),
    ("@@ICON_SVG@@",        "47_icon.svg",      "GTT_ICON_EOF"),
    ("@@VOICE_SEX_JSON@@",  "voice_sex.json",   "GTT_VOICESEX_JSON_EOF"),
]


def version():
    m = re.search(r"^VERSION\s*=\s*(\d+)", open(APP).read(), re.M)
    if not m:
        sys.exit("no VERSION in src/10_app.py")
    return int(m.group(1))


def sha(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()[:12]


def page_inlined():
    """The page is an HTML file, not a python string.

    It used to be a triple-quoted literal, and a patch written for it went
    through two levels of escaping: a \\' meant to reach the JavaScript as \'
    arrived as a bare quote and every onclick lost its argument. The whole
    script then died at parse, which on the phone looked like "counting the
    cache" forever and a SPEAK button that did nothing.

    An HTML file cannot do that to itself. And tests/test1 runs `node --check`
    over this script, so a syntax error stops the build rather than the app."""
    html = open(PAGE).read()
    if "GTT_APP_EOF" in html:
        sys.exit("the page contains the app heredoc marker")
    return html


def seed_block():
    """The preview cache, shipped in the installer.

    A preview is the same request every time, so the FIRST press does not have
    to cost anything either. These were generated once, here, and they land in
    the cache at install: every direction on the default voice and every voice
    on Neutral, as far as the daily wall allowed on the day they were made.
    Anything missing fills itself in the first time it is pressed.

    base64 in a heredoc, because the installer is one file and one file cannot
    carry raw bytes. About a megabyte, which buys sixty-odd requests that would
    otherwise come out of a ten-a-day budget."""
    import base64 as b64
    if not os.path.isdir(SEED):
        return ""
    out = []
    for f in sorted(os.listdir(SEED)):
        if not f.endswith(".mp3"):
            continue
        data = b64.b64encode(open(os.path.join(SEED, f), "rb").read()).decode()
        out.append("%s %s" % (f, data))
    return "\n".join(out)


def engine_swapped():
    """The vendored page with its engine replaced. Loud on a missing anchor: a
    silent no-op here would ship the upstream app still calling AssemblyAI."""
    html = open(TRANSCRIBE).read()
    for old, new in engine_patches.PATCHES:
        if old not in html:
            sys.exit("engine anchor is no longer in src/30_transcribe.html:\n    %s"
                     % old.strip().splitlines()[0])
        html = html.replace(old, new, 1)
    return html


def build():
    v = version()
    name = "%d-google-tts-stt-v%d.sh" % (v, v)
    header = "\n".join([
        "# Generated by tools/build_installer.py. Do not edit this file.",
        "# Edit src/00_head.sh, src/10_app.py, src/20_tail.sh and build again.",
        "#",
        "#   src/00_head.sh   %s" % sha(HEAD),
        "#   src/30_transcribe.html   %s   vendored, engine swapped at build" % sha(TRANSCRIBE),
        "#   src/seed/                 %d cached previews" % len(
            [f for f in os.listdir(SEED) if f.endswith(".mp3")] if os.path.isdir(SEED) else []),
        "#   src/10_app.py    %s" % sha(APP),
        "#   src/15_page.html %s" % sha(PAGE),
        "#   src/20_tail.sh   %s" % sha(TAIL),
    ] + ["#   src/%-16s %s" % (f, sha(os.path.join(ROOT, "src", f)))
         for _t, f, _m in READER_PARTS])
    text = (open(HEAD).read()
            .replace("@@HEADER@@", header.split("\n", 1)[0].lstrip("# "))
            + "")
    # rebuild properly: head, then the stamped header block, then app, then tail
    head = open(HEAD).read()
    head = head.replace("# @@HEADER@@", header)
    head = head.replace("@@VERSION@@", "v%d" % v).replace("@@FILENAME@@", name)
    tail = open(TAIL).read().replace("@@VERSION@@", "v%d" % v).replace("@@FILENAME@@", name)
    app = open(APP).read()
    app = app.replace('PAGE = "@@PAGE@@"', "PAGE = " + repr(page_inlined()))
    if "GTT_APP_EOF" in app:
        sys.exit("src/10_app.py contains the heredoc marker, which would end it early")
    page = engine_swapped()
    if "GTT_TRANSCRIBE_EOF" in page:
        sys.exit("the vendored page contains the heredoc marker")
    tail = tail.replace("@@TRANSCRIBE_HTML@@", page)
    for token, fname, marker in READER_PARTS:
        path = os.path.join(ROOT, "src", fname)
        if not os.path.exists(path):
            sys.exit("missing src/%s, which the installer writes" % fname)
        body = open(path, encoding="utf-8").read()
        if marker in body:
            sys.exit("src/%s contains its own heredoc marker %s, which would "
                     "end it early" % (fname, marker))
        if token not in tail:
            sys.exit("src/20_tail.sh no longer has %s to fill" % token)
        tail = tail.replace(token, body.rstrip("\n"))
    seed = seed_block()
    tail = tail.replace("@@SEED_CACHE@@", seed)
    return name, head + app + tail


def main():
    name, text = build()
    out = os.path.join(ROOT, name)
    check = "--check" in sys.argv

    if check:
        if not os.path.exists(out):
            print("STALE: %s does not exist" % name)
            return 1
        if open(out).read() != text:
            print("STALE: %s does not match the sources" % name)
            return 1
        # and there must be exactly one installer in the root
        others = [f for f in os.listdir(ROOT)
                  if re.match(r"^\d+-google-tts-stt-v\d+\.sh$", f) and f != name]
        if others:
            print("STALE: old installers still here: %s" % ", ".join(others))
            return 1
        latest = os.path.join(ROOT, "LATEST")
        if not os.path.exists(latest) or open(latest).read().strip() != name:
            print("STALE: LATEST does not say %s" % name)
            return 1
        # THE VERSION MUST HAVE BEEN BUMPED FOR THIS CHANGE.
        #
        # --check proved the installer matches src/. It did not prove the
        # NUMBER moved, and on 18.9.2026 that gap shipped nine different
        # installers all called v23, each one overwriting the last on GitHub.
        # gtt-update compares numbers, so a phone already on v23 was told
        # "already on v23, nothing to do" and could not receive any of them.
        #
        # modules/versioning.md: every change is a new number, and never
        # overwrite a file that has left the machine. This is that rule with
        # a check behind it: if the installer differs from the committed copy
        # under the same name, the number is stale.
        # The try wraps ONLY the git calls, and only because git may be
        # absent. It used to wrap the whole block including the message, which
        # referred to a variable that is not in scope here — so the guard
        # raised NameError on the line that was supposed to report the
        # problem, the bare except swallowed it, and the check printed
        # "fresh". A guard inside a blanket except is a guard that can fail
        # silently, which is the thing it was written to prevent.
        tracked = changed = False
        try:
            tracked = subprocess.run(
                ["git", "-C", ROOT, "ls-files", "--error-unmatch", name],
                capture_output=True).returncode == 0
            if tracked:
                changed = subprocess.run(
                    ["git", "-C", ROOT, "diff", "--quiet", "HEAD", "--", name],
                    capture_output=True).returncode != 0
        except OSError:
            pass                       # no git here: nothing to compare against
        if tracked and changed:
            print("STALE: %s has changed but VERSION is still %d.\n"
                  "       Every change is a new number "
                  "(modules/versioning.md §1)." % (name, version()))
            return 1
        print("fresh: %s" % name)
        return 0

    for f in os.listdir(ROOT):
        if re.match(r"^\d+-google-tts-stt-v\d+\.sh$", f) and f != name:
            os.remove(os.path.join(ROOT, f))
            print("removed old %s" % f)
    open(out, "w").write(text)
    os.chmod(out, 0o755)
    # LATEST names the current installer, so get.sh and gtt-update can ask raw
    # githubusercontent instead of the API. Raw is a CDN with no per-IP hourly
    # limit; the API gives an unauthenticated caller sixty an hour, shared with
    # everyone behind the same address. On mobile data that is a carrier.
    open(os.path.join(ROOT, "LATEST"), "w").write(name + "\n")
    r = subprocess.run(["bash", "-n", out], capture_output=True)
    if r.returncode != 0:
        print(r.stderr.decode())
        sys.exit("the generated installer is not valid shell")
    print("wrote %s, %d lines, shell syntax ok" % (name, text.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
