#!/usr/bin/env python3
"""
build_installer.py

The app is three sources. What ships is one file. Writing the Python twice,
once as source and once inside the shell script, is the failure the manifest
names by name: two copies with a rule about keeping them in step are still two
copies, and the rule is eventually not followed. So the installer is GENERATED,
the sources are the truth, and --check fails when the shipped file is stale.

    python3 tools/build_installer.py            write the installer
    python3 tools/build_installer.py --check    exit 1 if it is stale

The version comes from src/10_app.py, from VERSION, and from nowhere else.
The filename carries that number at both ends, per modules/versioning.md.
"""

import hashlib, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEAD = os.path.join(ROOT, "src", "00_head.sh")
APP = os.path.join(ROOT, "src", "10_app.py")
TAIL = os.path.join(ROOT, "src", "20_tail.sh")


def version():
    m = re.search(r"^VERSION\s*=\s*(\d+)", open(APP).read(), re.M)
    if not m:
        sys.exit("no VERSION in src/10_app.py")
    return int(m.group(1))


def sha(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()[:12]


def build():
    v = version()
    name = "%d-google-tts-stt-v%d.sh" % (v, v)
    header = "\n".join([
        "# Generated by tools/build_installer.py. Do not edit this file.",
        "# Edit src/00_head.sh, src/10_app.py, src/20_tail.sh and build again.",
        "#",
        "#   src/00_head.sh   %s" % sha(HEAD),
        "#   src/10_app.py    %s" % sha(APP),
        "#   src/20_tail.sh   %s" % sha(TAIL),
    ])
    text = (open(HEAD).read()
            .replace("@@HEADER@@", header.split("\n", 1)[0].lstrip("# "))
            + "")
    # rebuild properly: head, then the stamped header block, then app, then tail
    head = open(HEAD).read()
    head = head.replace("# @@HEADER@@", header)
    head = head.replace("@@VERSION@@", "v%d" % v).replace("@@FILENAME@@", name)
    tail = open(TAIL).read().replace("@@VERSION@@", "v%d" % v).replace("@@FILENAME@@", name)
    app = open(APP).read()
    if "GTT_APP_EOF" in app:
        sys.exit("src/10_app.py contains the heredoc marker, which would end it early")
    return name, head + app + tail


def main():
    name, text = build()
    out = os.path.join(ROOT, name)
    check = "--check" in sys.argv

    if check:
        if not os.path.exists(out):
            print("STALE: %s does not exist" % name)
            return 1
        if open(out).read() != text:
            print("STALE: %s does not match the sources" % name)
            return 1
        # and there must be exactly one installer in the root
        others = [f for f in os.listdir(ROOT)
                  if re.match(r"^\d+-google-tts-stt-v\d+\.sh$", f) and f != name]
        if others:
            print("STALE: old installers still here: %s" % ", ".join(others))
            return 1
        latest = os.path.join(ROOT, "LATEST")
        if not os.path.exists(latest) or open(latest).read().strip() != name:
            print("STALE: LATEST does not say %s" % name)
            return 1
        print("fresh: %s" % name)
        return 0

    for f in os.listdir(ROOT):
        if re.match(r"^\d+-google-tts-stt-v\d+\.sh$", f) and f != name:
            os.remove(os.path.join(ROOT, f))
            print("removed old %s" % f)
    open(out, "w").write(text)
    os.chmod(out, 0o755)
    # LATEST names the current installer, so get.sh and gtt-update can ask raw
    # githubusercontent instead of the API. Raw is a CDN with no per-IP hourly
    # limit; the API gives an unauthenticated caller sixty an hour, shared with
    # everyone behind the same address. On mobile data that is a carrier.
    open(os.path.join(ROOT, "LATEST"), "w").write(name + "\n")
    r = subprocess.run(["bash", "-n", out], capture_output=True)
    if r.returncode != 0:
        print(r.stderr.decode())
        sys.exit("the generated installer is not valid shell")
    print("wrote %s, %d lines, shell syntax ok" % (name, text.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
